ApplicationPsiko/ApplicationPsiko.Web/Controllers/AppFormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PsikoApp.ModelData;
using PsikoApp.ModelAccess;
using PsikoApp.ModelView;

namespace ApplicationPsiko.Web.Controllers
{
    public class AppFormController : Controller
    {
        // GET
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult IndexList()
        {
            return View();
        }

        public ActionResult List()
        {
            List<app_formView> list = AppFormRepo.All();
            return PartialView("_List", list);
        }

        //Get
        public ActionResult Create()
        {
            return PartialView("_Create");
        }

        [HttpPost]
        public ActionResult Create(app_formView model)
        {
            ResponseResult result = AppFormRepo.Create(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Edit(long id_form)
        {
            return PartialView("_Edit", AppFormRepo.ById(id_form));
        }

        [HttpPost]
        public ActionResult Edit(app_formView model)
        {
            ResponseResult result = AppFormRepo.Edit(model);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message,
                    entity = result.Entity
                },
                JsonRequestBehavior.AllowGet);
        }

        //Get
        public ActionResult Delete(long id_form)
        {
            return PartialView("_Delete", AppFormRepo.ById(id_form));
        }

        [HttpPost]
        public ActionResult Delete(app_formView model)
        {
            ResponseResult result = AppFormRepo.Delete(model.id_form);
            return Json(
                new
                {
                    success = result.Success,
                    message = result.Message
                },
                JsonRequestBehavior.AllowGet);

        }
    }
}

ApplicationPsiko/ApplicationPsiko.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ApplicationPsiko.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ApplicationPsiko/ApplicationPsiko.Web/Views/AppForm/Index.cshtml
<div class="row text-center">
    <div class="col-md-1 col-md-offset-2">
        <img src="~/Folderxsis/xsis.jpeg" alt="Xsis" width="130" />
    </div>
    <div class="col-md-8" style="color: steelblue">
        <h1><b>Welcome to PT. Xsis Mitra <br /> Utama</b></h1> <br />
        <div style="font-size:18px"> We offers you the chance to join with us and expand your talent, skill <br /> and experience in IT industry. </div> <br />
        <div class="alert alert-success col-md-offset-1 col-md-9" role="alert">
            <i class="text-center" style="color:steelblue; font-size:18px">To apply, please fill out all the required personal information (information with red stars must strictly be filled) and then submit your form. For the next process , we will inform you by phone, sms or email (from recruitment@xsis.co.id).</i>
        </div>
    </div>
</div>

<div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <b>Application Form</b>
            </h3>
        </div>
        <div class="panel-body">
            Loading...
        </div>
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 500px">
        <div class="modal-content">
            <div class="modal-header" style="background: darkred">
                <button type="button" style="color: white" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" style="color: white">Hapus ?</h3>
            </div>
            <div class="modal-body" id="body-delete">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetForm()
        })

        function GetForm() {
            $.ajax({
                url: '@Url.Action("Create", "AppForm")',
                type: 'get',
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "AppForm")',
                type: 'get',
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        function GetById(id_form) {
            $.ajax({
                url: '@Url.Action("Edit", "AppForm")',
                type: 'get',
                data: { id_form: id_form },
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        function DeleteById(id_form) {
            $.ajax({
                url: '@Url.Action("Delete", "AppForm")',
                type: 'get',
                data: { id_form: id_form },
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                }
            });
        }
    </script>
}

ApplicationPsiko/ApplicationPsiko.Web/Views/AppForm/IndexList.cshtml
<div class="row text-center">
    <div class="col-md-1 col-md-offset-2">
        <img src="~/Folderxsis/xsis.jpeg" alt="Xsis" width="130" />
    </div>
    <div class="col-md-8" style="color: steelblue">
        <h1><b>Welcome to PT. Xsis Mitra <br /> Utama</b></h1> <br />
        <div style="font-size:18px"> We offers you the chance to join with us and expand your talent, skill <br /> and experience in IT industry. </div> <br />
    </div>
</div>

<div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <b>Application Form</b>
            </h3>
        </div>
        <div class="panel-body">
            Loading...
        </div>
    </div>
</div>

<div id="modal1" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document" style="width: 500px">
        <div class="modal-content">
            <div class="modal-header" style="background: darkred">
                <button type="button" style="color: white" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h3 class="modal-title" style="color: white">Hapus ?</h3>
            </div>
            <div class="modal-body" id="body-delete">
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            GetList()
        })

        function GetList() {
            $.ajax({
                url: '@Url.Action("List", "AppForm")',
                type: 'get',
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        function GetById(id_form) {
            $.ajax({
                url: '@Url.Action("Edit", "AppForm")',
                type: 'get',
                data: { id_form: id_form },
                success: function (result) {
                    $(".panel-body").html(result);
                }
            });
        }

        function DeleteById(id_form) {
            $.ajax({
                url: '@Url.Action("Delete", "AppForm")',
                type: 'get',
                data: { id_form: id_form },
                success: function (result) {
                    $(".modal-body").html(result);
                    $("#modal1").modal("show");
                }
            });
        }
    </script>
}

ApplicationPsiko/ApplicationPsiko.Web/Views/AppForm/_Delete.cshtml
@model PsikoApp.ModelView.app_formView

<div>
    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-1 col-md-offset-1">
                <span class="glyphicon glyphicon-trash" style="font-size: 60px; color: darkred"></span>
            </div>
            <div class="col-md-8 text-left" style="font-size: 15px; left: 30px">
                Anda yakin ingin menghapus form applicant? <br />
                Name : <b>@Html.DisplayFor(model => model.name)</b> <br />
                Position Apply : <b>@Html.DisplayFor(model => model.position)</b>
            </div>
        </div>
    </div>

    @using (Html.BeginForm("Delete", "AppForm", FormMethod.Post, new { id = "form-delete", name = "form-delete" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.id_form)
        <div class="text-right">
            <div class="form-actions btn-group btn-group-md">
                <input type="button" value="Tidak" data-dismiss="modal" class="btn btn-warning" style="width: 100px" />
                <input type="submit" value="Ya" class="btn btn-danger" style="width: 100px" />
            </div>
        </div>
    }
</div>

<script type="text/javascript">
    $("#form-delete").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert('Form Applicant berhasil dihapus');
                    $("#modal1").modal("hide");
                    GetList()
                } else {
                    alert('Error: ' + result.message);
                }
            }
        })
        return false;
    })
</script>

ApplicationPsiko/ApplicationPsiko.Web/Views/AppForm/_Edit.cshtml
@model PsikoApp.ModelView.app_formView

@using (Html.BeginForm("Edit", "AppForm", FormMethod.Post, new { id = "form-edit", name = "form-edit" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Name : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Mobile Phone Number : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px", placeholder = "0888888888", type="number" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Alternative Phone Number : </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.phone_alt, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px" } })
                @Html.ValidationMessageFor(model => model.phone_alt, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Email : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px", placeholder = "yourEmail@yahoo.com" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Place of Birth : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.pob, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px" } })
                @Html.ValidationMessageFor(model => model.pob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Date Of Birth : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.dob_y,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "1980" , Text = "1980" },
                       new SelectListItem { Value = "1981" , Text = "1981" },
                       new SelectListItem { Value = "1982" , Text = "1982" },
                       new SelectListItem { Value = "1983" , Text = "1983" },
                       new SelectListItem { Value = "1984" , Text = "1984" },
                       new SelectListItem { Value = "1985" , Text = "1985" },
                       new SelectListItem { Value = "1986" , Text = "1986" },
                       new SelectListItem { Value = "1987" , Text = "1987" },
                       new SelectListItem { Value = "1988" , Text = "1988" },
                       new SelectListItem { Value = "1989" , Text = "1989" },
                       new SelectListItem { Value = "1990" , Text = "1990" },
                       new SelectListItem { Value = "1991" , Text = "1991" },
                       new SelectListItem { Value = "1992" , Text = "1992" },
                       new SelectListItem { Value = "1993" , Text = "1993" },
                       new SelectListItem { Value = "1994" , Text = "1994" },
                       new SelectListItem { Value = "1995" , Text = "1995" },
                       new SelectListItem { Value = "1996" , Text = "1996" },
                       new SelectListItem { Value = "1997" , Text = "1997" },
                       new SelectListItem { Value = "1998" , Text = "1998" },
                       new SelectListItem { Value = "1999" , Text = "1999" },
                       new SelectListItem { Value = "2000" , Text = "2000" },
                       new SelectListItem { Value = "2001" , Text = "2001" },
                       new SelectListItem { Value = "2002" , Text = "2002" },
                       new SelectListItem { Value = "2003" , Text = "2003" },
                       new SelectListItem { Value = "2004" , Text = "2004" },
                       new SelectListItem { Value = "2005" , Text = "2005" },
                       new SelectListItem { Value = "2006" , Text = "2006" },
                       new SelectListItem { Value = "2007" , Text = "2007" },
                       new SelectListItem { Value = "2008" , Text = "2008" },
                       new SelectListItem { Value = "2009" , Text = "2009" },
                       new SelectListItem { Value = "2010" , Text = "2010" },
                       new SelectListItem { Value = "2011" , Text = "2011" },
                       new SelectListItem { Value = "2012" , Text = "2012" },
                       new SelectListItem { Value = "2013" , Text = "2013" },
                       new SelectListItem { Value = "2014" , Text = "2014" },
                       new SelectListItem { Value = "2015" , Text = "2015" },
                       new SelectListItem { Value = "2016" , Text = "2016" },
                       new SelectListItem { Value = "2017" , Text = "2017" },
                       new SelectListItem { Value = "2018" , Text = "2018" },
                       new SelectListItem { Value = "2019" , Text = "2019" },
                       new SelectListItem { Value = "2020" , Text = "2020" }
                    }, new { @class = "select-dob" })

                @Html.DropDownListFor(model => model.dob_m,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "Jan" , Text = "Jan" },
                       new SelectListItem { Value = "Feb" , Text = "Feb" },
                       new SelectListItem { Value = "Mar" , Text = "Mar" },
                       new SelectListItem { Value = "Apr" , Text = "Apr" },
                       new SelectListItem { Value = "May" , Text = "May" },
                       new SelectListItem { Value = "Jun" , Text = "Jun" },
                       new SelectListItem { Value = "Jul" , Text = "Jul" },
                       new SelectListItem { Value = "Aug" , Text = "Aug" },
                       new SelectListItem { Value = "Sep" , Text = "Sep" },
                       new SelectListItem { Value = "Oct" , Text = "Oct" },
                       new SelectListItem { Value = "Nov" , Text = "Nov" },
                       new SelectListItem { Value = "Dec" , Text = "Dec" }
                    }, new { @class = "select-dob" })


                @Html.DropDownListFor(model => model.dob_d,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "1" , Text = "1" },
                       new SelectListItem { Value = "2" , Text = "2" },
                       new SelectListItem { Value = "3" , Text = "3" },
                       new SelectListItem { Value = "4" , Text = "4" },
                       new SelectListItem { Value = "5" , Text = "5" },
                       new SelectListItem { Value = "6" , Text = "6" },
                       new SelectListItem { Value = "7" , Text = "7" },
                       new SelectListItem { Value = "8" , Text = "8" },
                       new SelectListItem { Value = "9" , Text = "9" },
                       new SelectListItem { Value = "10" , Text = "10" },
                       new SelectListItem { Value = "11" , Text = "11" },
                       new SelectListItem { Value = "12" , Text = "12" },
                       new SelectListItem { Value = "13" , Text = "13" },
                       new SelectListItem { Value = "14" , Text = "14" },
                       new SelectListItem { Value = "15" , Text = "15" },
                       new SelectListItem { Value = "16" , Text = "16" },
                       new SelectListItem { Value = "17" , Text = "17" },
                       new SelectListItem { Value = "18" , Text = "18" },
                       new SelectListItem { Value = "19" , Text = "19" },
                       new SelectListItem { Value = "10" , Text = "10" },
                       new SelectListItem { Value = "21" , Text = "21" },
                       new SelectListItem { Value = "22" , Text = "22" },
                       new SelectListItem { Value = "23" , Text = "23" },
                       new SelectListItem { Value = "24" , Text = "24" },
                       new SelectListItem { Value = "25" , Text = "25" },
                       new SelectListItem { Value = "26" , Text = "26" },
                       new SelectListItem { Value = "27" , Text = "27" },
                       new SelectListItem { Value = "28" , Text = "28" },
                       new SelectListItem { Value = "29" , Text = "29" },
                       new SelectListItem { Value = "30" , Text = "30" },
                       new SelectListItem { Value = "31" , Text = "31" }
                    }, new { @class = "select-dob" })

                @Html.ValidationMessageFor(model => model.dob, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Last Education : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.last_edu,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "S2/S3" , Text = "S2/S3" },
                       new SelectListItem { Value = "S1/D4" , Text = "S1/D4" },
                       new SelectListItem { Value = "D3" , Text = "D3" },
                       new SelectListItem { Value = "SMU/SMK" , Text = "SMU/SMK" }
                    }, "-- Choose --", new { @class = "form-control", style = "max-width: 400px" })
                @Html.ValidationMessageFor(model => model.last_edu, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">College / University : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.univ, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px" } })
                @Html.ValidationMessageFor(model => model.univ, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Major : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.major, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px" } })
                @Html.ValidationMessageFor(model => model.major, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Position Apply : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.EditorFor(model => model.position, new { htmlAttributes = new { @class = "form-control", style = "max-width: 400px" } })
                @Html.ValidationMessageFor(model => model.position, "", new { @class = "text-danger" })
            </div>
        </div>
        <b><i>How did you come to know of this vacancy ?</i></b> <br /><br />
        <div class="form-group">
            <div class="col-md-4 text-right" style="font-weight: bold">Source : <b style="color:darkred">*</b> </div>
            <div class="col-md-8">
                @Html.DropDownListFor(model => model.source,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "Event" , Text = "Event" },
                       new SelectListItem { Value = "Career Center" , Text = "Career Center" },
                       new SelectListItem { Value = "Referral Program" , Text = "Referral Program" }
                    }, "-- Choose --", new { @class = "form-control", style = "max-width: 400px" })
                @Html.ValidationMessageFor(model => model.source, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
                <input type="reset" value="Reset" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script type="text/javascript">
    $("#form-edit").submit(function () {
        $.ajax({
            url: this.action,
            type: this.method,
            data: $(this).serialize(),
            success: function (result) {
                if (result.success) {
                    alert(`Form berhasil diedit`);
                    GetList()
                }
            }
        })
        return false;
    })
</script>

ApplicationPsiko/ApplicationPsiko.Web/Views/AppForm/_List.cshtml
@model IEnumerable<PsikoApp.ModelView.app_formView>

    <table class="table">
        <tr>
            <th>
                Applicant
            </th>
            <th>Action</th>
        </tr>
    
        @foreach (var item in Model) 
         {
            <tr>
                <td>
                    <div class="row">
                        <p class="col-md-4" style="font-size:12px">Name</p>
                        <div class="col-md-8" style="font-weight: bold">
                            @Html.DisplayFor(modelItem => item.name)
                        </div>
                    </div>

                    <div class="row">
                        <p class="col-md-4" style="font-size:12px">Phone Number</p>
                        <div class="col-md-8" style="font-weight: bold">
                            @Html.DisplayFor(modelItem => item.phone)
                        </div>
                    </div>

                    <div class="row">
                        <p class="col-md-4" style="font-size:12px">Email</p>
                        <div class="col-md-8" style="font-weight: bold">
                            @Html.DisplayFor(modelItem => item.email)
                        </div>
                    </div>

                    <div class="row">
                        <p class="col-md-4" style="font-size:12px">Position Apply</p>
                        <div class="col-md-8" style="font-weight: bold">
                            @Html.DisplayFor(modelItem => item.position)
                        </div>
                    </div>
                </td>

                <td>
                    <div class="btn-group btn-group-sm">
                        <button type="button" class="btn btn-warning btn-edit" data-id="@item.id_form" title="Edit" onclick="GetById(@item.id_form)">Edit</button>
                        <button type="button" class="btn btn-danger btn-delete" data-id="@item.id_form" onclick="DeleteById(@item.id_form)" title="Delete">Delete</button>
                    </div>
                </td>
            </tr>
         }
    
    </table>

ApplicationPsiko/ApplicationPsiko.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color: #121e79">
        <div class="container">
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Application Form", "Index", "AppForm")</li>
                    <li>@Html.ActionLink("List Applicant", "IndexList", "AppForm")</li>
                </ul>
            </div>
        </div>
    </div>

    <br />
    <div class="container body-content">
        @RenderBody()
    </div>

    <footer class="col-md-offset-1">
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

</body>
</html>